## NOTE: 
# Passwords and other sensitive data belongs into an .env file.
# see https://docs.docker.com/compose/environment-variables/set-environment-variables/ 

version: "3.9"

volumes:
  grafana-storage:
  grafana-postgres:
  timescale:

networks:
  default:
    name: prefect-network

services:
  grafana:
    # image: grafana/grafana-oss:latest
    image: grafana-custom
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=grafana-db:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=postgres
      - GF_DATABASE_SSL_MODE=disable
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - grafana-db
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"

  grafana-db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=grafana
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grafana
    ports:
      - 5433:5432
    volumes: 
      - grafana-postgres:/var/lib/postgresql/data
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"

  timescaledb:
    image: timescale/timescaledb-ha:pg14.6-ts2.9.2-latest
    environment:
      - POSTGRES_PASSWORD=password    # required, otherwise timescale disable password check for all dbs 
    ports:
      - 5431:5432
    volumes: 
      - timescale:/home/postgres/pgdata/data
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"
