version: "3.9"

networks:
  default:
    name: monitoring-network

volumes:
  mimir-1-data:
  mimir-2-data:
  minio-data:

services:  
  minio-mimir:
    image: minio/minio
    container_name: minio-mimir
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/mimir && \
        minio server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    volumes:
      - minio-data:/data
    ports:
      - 9014:9000
      - 9016:9001
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  load-balancer:
    image: nginx:latest
    container_name: mimir-load-balancer
    volumes:
      - ./mimir-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "mimir-1"
      - "mimir-2"
      # - "mimir-3"
    ports:
      - 9009:9009
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  mimir-1:
    image: grafana/mimir:latest
    container_name: mimir-1
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-1
    depends_on:
      - minio-mimir
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - ./mimir/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-1-data:/data
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  mimir-2:
    image: grafana/mimir:latest
    container_name: mimir-2
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-2
    depends_on:
      - minio-mimir
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - ./mimir/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-2-data:/data
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  prometheus-mimir:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus-config-mimir.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
