version: "3.9"

networks:
  default:
    name: monitoring-network

volumes:
  minio:

services:
  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    environment:
      # the default
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    ports:
      - 9004:9000
      - 9006:9001
    volumes:
      - minio:/data
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
    #   interval: 15s
    #   timeout: 20s
    #   retries: 5

  loki:
    image: grafana/loki:2.7.4
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    depends_on:
      - minio
    #!! don't use the plugin driver here - this prohibits stopping loki
    # see https://github.com/grafana/loki/issues/2063 for a workaround

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro


  prometheus:
    image: prom/prometheus
    volumes:
    - ./prometheus/prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - cadvisor
    - loki
    ports:
      - "9090:9090"
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"

  ## in the current setup promtail has no task 
  ## additionaly it fails because the by the config defined path does not exist
  #
  # promtail:
  #   image: grafana/promtail:2.7.4
  #   volumes:
  #     - /var/log:/var/log
  #     - ./promtail:/etc/promtail
  #   # ports:
  #   #   - "1514:1514" # this is only needed if you are going to send syslogs
  #   restart: unless-stopped
  #   command: -config.file=/etc/promtail/promtail-config.yml
