version: "3.9"

networks:
  default:
    name: monitoring-network

volumes:
  minio:

services:
  minio:
    image: minio/minio
    container_name: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    environment:
      # the default
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    ports:
      - 9004:9000
      - 9006:9001
    volumes:
      - minio:/data
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
    #   interval: 15s
    #   timeout: 20s
    #   retries: 5
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  loki:
    image: grafana/loki:2.7.4
    container_name: loki
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    depends_on:
      - minio
    #!! don't use the plugin driver here - this prohibits stopping loki
    # see https://github.com/grafana/loki/issues/2063 for a workaround

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
    - ./prometheus/prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - cadvisor
    - loki
    ports:
      - "9090:9090"
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  # additionaly it fails because the by the config defined path does not exist
  
  promtail:
    image: grafana/promtail:2.7.4
    container_name: promtail
    volumes:
      - ./promtail_logs:/var/log
      - ./promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    
