# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  # http_listen_address: 127.0.0.1
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-gateway:80/loki/api/v1/push
    tenant_id: 1 # see https://github.com/grafana/loki/issues/7081

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
  
  - job_name: kidip_logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: kidip
        __path__: /var/log/*log
  

# local machine logs
# scrape_configs:
# - job_name: local
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: varlogs
#       __path__: /var/log/*log
  

## docker logs
# scrape_configs:
#   - job_name: docker 
#     pipeline_stages:
#       - docker: {}
#     static_configs:
#       - labels:
#         job: docker
#         __path__: /var/lib/docker/containers/*/*-json.log

# syslog target

#- job_name: syslog
#  syslog:
#    listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#    idle_timeout: 60s
#    label_structured_data: yes
#    labels:
#      job: "syslog"
#  relabel_configs:
#    - source_labels: ['__syslog_message_hostname']
#      target_label: 'host'
