# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  # http_listen_address: 127.0.0.1
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-gateway:80/loki/api/v1/push
    tenant_id: 1 # see https://github.com/grafana/loki/issues/7081

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "logstream"
      - source_labels: ["__meta_docker_container_label_logging_jobname"]
        target_label: "job"

  # # old config
  # - job_name: app_logs
  #   pipeline_stages:
  #     - regex:
  #         expression: '(?P<ts>^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z)\|-\|.*\|(?P<service>\S+)\|\*\|0\|(?P<level>[a-z]{3})\|Y\|(?P<message>.+)$' # works kinda
  #         # expression: '(?P<ts>^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z)\|-\|(?P<message>.+)$'
  #     - timestamp:
  #         source: ts
  #         format: RFC3339      #https://github.com/jafernandez73/grafana-loki/blob/master/docs/logentry/processing-log-lines.md#match
  #     - match:
  #         selector: '{job="app_logs"} |~ ".*TO_DFB.*"'
  #         action: keep
  #         stages:
  #           - regex:
  #               expression: 'TO_DFB\.(?P<commodity>.+)\.(?P<data>.+)'
  #               source: service
  #           - labels:
  #               commodity:
  #               data:
  #           - static_labels:
  #               service: TO_DFB
  #     - labels:
  #         level: level
  #     # - replace:
  #     #     expression: 'msg'
  #     #     source:     level
  #     #     replace: 'info'
  #     - output:
  #         source: message
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: app_logs
  #         app: AppName
  #         server: 'my.server.domain.net'
  #         __path__: /var/log/*log

  # reduced labels
  - job_name: app_logs
    pipeline_stages:
      - regex:
          # expression: '(?P<ts>^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z)\|-\|.*\|(?P<service>\S+)\|\*\|0\|(?P<level>[a-z]{3})\|Y\|(?P<message>.+)$' # works kinda
          expression: '(?P<ts>^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z)\|-\|(?P<message>.+)$'
      - timestamp:
          source: ts
          format: RFC3339 #https://github.com/jafernandez73/grafana-loki/blob/master/docs/logentry/processing-log-lines.md#match
      # - match:
      #     selector: '{job="app_logs"} |~ ".*TO_DFB.*"'
      #     action: keep
      #     stages:
      #       - regex:
      #           expression: 'TO_DFB\.(?P<commodity>.+)\.(?P<data>.+)'
      #           source: service
      #       - labels:
      #           commodity:
      #           data:
      #       - static_labels:
      #           service: TO_DFB
      # - labels:
      #     level: level
      # - replace:
      #     expression: 'msg'
      #     source:     level
      #     replace: 'info'
      - output:
          source: message
    static_configs:
      - targets:
          - localhost
        labels:
          job: app_logs
          # app: AppName
          # server: 'my.server.domain.net'
          __path__: /var/log/*log

  - job_name: app_logs_2
    pipeline_stages:
      - multiline:
          # Identify timestamps as first line of a multiline block. Enclose the string in single quotes.
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{4}'
          max_wait_time: 3s
      - regex:
          # expression: '(?P<ts>^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z)\|-\|.*\|(?P<service>\S+)\|\*\|0\|(?P<level>[a-z]{3})\|Y\|(?P<message>.+)$' # works kinda
          expression: '(?P<ts>^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\.\d{4}\|0\|(?P<message>.+)$'
      - timestamp:
          source: ts
          format: "2006-01-02 15:04:05" #https://github.com/jafernandez73/grafana-loki/blob/master/docs/logentry/processing-log-lines.md#match
      - output:
          source: message
    static_configs:
      - targets:
          - localhost
        labels:
          job: app_logs
          # app: AppName
          # server: 'my.server.domain.net'
          __path__: /var/log/*.logs
## local machine logs
# scrape_configs:
# - job_name: local
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: varlogs
#       __path__: /var/log/*log

## docker logs
# scrape_configs:
#   - job_name: docker
#     pipeline_stages:
#       - docker: {}
#     static_configs:
#       - labels:
#         job: docker
#         __path__: /var/lib/docker/containers/*/*-json.log

## syslog target
# scrape_configs:
#- job_name: syslog
#  syslog:
#    listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#    idle_timeout: 60s
#    label_structured_data: yes
#    labels:
#      job: "syslog"
#  relabel_configs:
#    - source_labels: ['__syslog_message_hostname']
#      target_label: 'host'
